name: CI
on:
  
  push:
    branches: [ main ]
    
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v2
      
      - name: Get default branch from origin      
        id: get-origin-default-branch
        uses: pipeline-foundation/get-origin-def-branch@v1.0.0



      - name: Run a multi-line script
        run: |

          
              ${{ steps.get-origin-default-branch.outputs.default_branch }}
          
              echo "The default branch of this repository is ${{ steps.get-origin-default-branch.outputs.default_branch }}"


