name: CI
on:
  
  push:
    branches: [ main ]
    
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v1
      

      - name: Get default branch from origin of owner/repo
        id: get-origin-default-branch
        uses: pipeline-foundation/get-origin-def-branch@v1.0.0


      - name: Run a multi-line script
        run: |

          

          
              echo "The default branch of this repository is ${{ steps.get-origin-default-branch.outputs.default_branch }}"


